# Generated by Django 4.2.30 on 2026-07-27 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=32)),
            ],
            options={
                'unique_together': {('channel', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('conversions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='ads.campaign')),
            ],
            options={
                'unique_together': {('campaign', 'date')},
            },
        ),
    ]
